kind = "web"
previewPath = "/"
title = "HutaoTik"
version = "1.0.0"
id = "artifacts/hutaotik"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22394

[services.development]
run = "pnpm --filter @workspace/hutaotik run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hutaotik", "run", "build" ]
publicDir = "artifacts/hutaotik/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22394"
BASE_PATH = "/"
